@startuml project

skinparam classAttributeIconSize 0

note as mainNote
    Multiplicities are 1:1 by default
    T stereotypes are template instantiations
end note

() main
class Player{
    -position : Vector2
    -speed : float
    +move(Vector2)
    +getPos() : Vector2
    +getSpeed() : float
}
class PlayerListener{

}

main --> Player
main --> PlayerListener

package utils{
    class Bag<type>{
        -content : unordered_set<type>
        +add(type)
        +remove(type)
        +foreach(function<void(type)>&)
    }
    class "Bag<Listener*>" as BagListener <<(T,LightBlue)>>

    class Singleton<type>{
        {static} -object : type&
        {static} -initialised : bool
        -Singleton()
        {static} +create(const type&)
        {static} +instance() : const type&
    }
    class "Singleton<EventDispatcher>" as SingletonEventDispatcher <<(T,LightBlue)>>
}

BagListener ..|> Bag
SingletonEventDispatcher ..|> Singleton

package event{
    interface Event
    interface Listener{
        +onEvent(Event&)
    }
    class Observable{
        +subscribe(Listener&)
        +unsubscribe(Listener&)
        +fireEvent(Event&)
    }
    class InputListener{
        {field} -inputTest : function<bool()>
        {field} -action : function<void()>
        {field} -actionElse : function<void()>
    }
    class EventDispatcher{
        +dispatch()
        +addInputListener(Listener&)
        +removeInputListener(Listener&)
    }
    class ActiveVariable<type>{
        -variable : type
        +get() : type
        +set(type)
        +addListener(Listener&)
        +removeListener(Listener&)
    }
}

Listener <|.. InputListener : +
Observable <|-- EventDispatcher : -
Observable <|-- ActiveVariable : -
Observable --> BagListener : listeners

InputListener --> EventDispatcher

package component{
    class Component{
        -position : Vector2
        -size : Vector2
        -shown : bool
        +getPos() : Vector2
        +setPos(Vector2)
        +getSize() : Vector2
        +setSize(Vector2)
        +fit()
        +draw()
        +show(bool)
    }
    class Button{
        -text : string
        -state : State
        -isMouseInside() : bool
        +setText(string)
        +setAction(Action)
    }
    class Action{
        -name : string
    }
    class Container{
        +add(Component&, int constraint)
        +remove(Component&, int constraint)
        +layout()
    }
    class Panel{

    }
    class Window{
        -title : String
        +setTitle(String)
        +init()
    }
}

Component <|-- Button : +
Observable <|-- Action : +
Component <|-- Container : +
Container <|-- Panel : +
Panel <|-- Window : +

Button --> Action
Button --> "2" InputListener

Window --> EventDispatcher
Window --> SingletonEventDispatcher

package layout{
    interface LayoutManager{
        +addComponent(Component, int constraint)
        +removeComponent(Component, int constraint)
    }
    abstract class OrientedLayout{
        -vertical : bool
        +isVertical() : bool
        +setVertical(bool)
    }
    class BorderLayout{

    }
    class StackLayout{

    }
    class LayeredLayout{

    }
}

LayoutManager <|-- OrientedLayout : +
OrientedLayout <|.. BorderLayout : +
OrientedLayout <|.. StackLayout : +
LayoutManager <|.. LayeredLayout : +

Container --> LayoutManager
BorderLayout --> "3" Component
StackLayout --> "*" Component
LayeredLayout --> "*" Component

PlayerListener --> "4" InputListener
PlayerListener --> Player

main --> Window
main --> Button

@enduml